### ISSUE TITLE
A few broken links

### ISSUE THREAD

**Issue by osnabrugge** [xUnholy/k8s-gitops#1642]
First of all, kudos on your repo as it's well thought out and I've discovered a few new tools that I will be reseachibg more.

Nothing major and didn't think opening an issue would qualify, but Flagger on your readme is actually linked to Falco,  I believe it should be their home page: https://falco.org/

Second one is when reviewing your page about giving feedback/contributing, most point back to a page on your repo that's not populated.

Once again, thanks for taking the time to make sure a decent repo and write up!

**Comment by xUnholy** [comment]
Thanks @osnabrugge I'll need to update and repair those links, appreciate that overall things have been helpful! 

Feel free to also join the Discord community for more direct contact and appreciate the help :)

**Comment by xUnholy** [comment]
Those links and items should all now be resolved 👍
