### ISSUE TITLE
Show the helm diff in a helm version change

### ISSUE THREAD

**Issue by xunholy** [xunholy/k8s-gitops#353]
# Details

Ideally, when a helm chart version is changed I want to view the detected resource changes. Even when these resources are managed by flux helm-controller it would be good to see the diff to know if there are fundamental breaking changes for charts that are more fragile (hold state).

https://github.com/databus23/helm-diff

**Comment by xUnholy** [comment]
Flux has committed to building this capability into their flux CLI

**Comment by Denissa89** [comment]
Hello!
https://fluxcd.io/docs/cmd/flux_diff_kustomization/

**Comment by onedr0p** [comment]
nice.
