### ISSUE TITLE
Setup Keycloak + oauth2 for nginx ingress

### ISSUE THREAD

**Issue by xUnholy** [xUnholy/k8s-gitops#70]
# Details

oauth2 proxy is currently setup with github and would be good to also setup with keycloak internal to the cluster.

https://github.com/keycloak/keycloak

https://github.com/codecentric/helm-charts

The image is currently not supported for arm64

**Comment by carpenike** [comment]
Heh, fancy seeing this. I'm gonna move forward with KeyCloak-gatekeeper in addition to KeyCloak in cluster. Allows for granular control over which URI elements need to be authenticated and which don't. For example, `/api` on services generally is protected by an api key and shouldn't be sent to oauth provider. I don't believe oauth2-proxy can get that granular.

Now I need to decide whether I want to add a conditional deployment for the gatekeeper proxy to every helm template that can't do native oauth or whether I use an external chart that deploys a separate proxy (https://hub.helm.sh/charts/gabibbo97/keycloak-gatekeeper). Advantage to the first option is that the proxy will be in the same pod as the service and enables access via localhost for the upstream config. Advantage for the second option is less updates to helm charts...

There's a third option which is to use proxy injector: https://github.com/stakater/ProxyInjector

**Comment by xUnholy** [comment]
Closing as nginx is no longer in use
