### ISSUE TITLE
Update MetalLB chart & remove hardcode references to tags

### ISSUE THREAD

**Issue by xUnholy** [xUnholy/k8s-gitops#75]
New Chart location: https://github.com/bitnami/charts/tree/master/bitnami/metallb

https://github.com/raspbernetes/k8s-gitops/blob/ef405eb40bab75e3d826c6f2a8a69de3de4fb7a2/namespaces/network/metallb/metallb.yaml#L20

**Comment by carpenike** [comment]
Move to BGP and remove metallb. :)

https://github.com/onedr0p/k3s-gitops/issues/67

**Comment by xUnholy** [comment]
@carpenike I could move to BGP but that feels like I'd be moving backwards in time, metallb does a really good job. What pros and cons are there to moving to BGP and ditching metallb all together?

**Comment by carpenike** [comment]
From my perspective, updated routes to the nodes that serve the application will always be the most ideal way to serve apps out of k8s. Metallb can operate in two functions, L2 -- which to my knowledge is essentially hijacking arp broadcasts for the IP addresses assigned via metallb, or L3 -- which also uses BGP similar to Calico. Only in this case you could cut out metallb altogether and use your CNI to perform that function natively.

**Comment by xUnholy** [comment]
Ignore my lack of understanding regarding BGP, is there any hardware requirement or management outside the cluster that needs to take place? Ideally, I shouldn't need to configure a router or anything external to my cluster. I know you've shared these before however, could you provide some of the examples of your setup with using BGP and Calico, interested to see what configuration difference it requires.

**Comment by carpenike** [comment]
Yup no problem. Yes there's configuration on your router. It's essentially a "I will accept route updates from this source" type configuration. Set it once and forget it.

For instance, my config in vyos:

```
ryan@vyos# show protocols bgp
 bgp 64512 {
     neighbor 10.20.10.10 {
         remote-as 64512
     }
     neighbor 10.20.10.11 {
         remote-as 64512
     }
     neighbor 10.20.10.12 {
         remote-as 64512
     }
     neighbor 10.20.10.15 {
         remote-as 64512
     }
     neighbor 10.20.10.16 {
         remote-as 64512
     }
     parameters {
         router-id 10.20.0.1
     }
 }
```
